import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import Header from "../components/Header";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["example.getAll"]);
  if (isLoading || !data) {
    return <div>Loading...</div>;
  }
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen w-screen items-stretch relative">
        <Header />

        <div className="flex flex-col justify-center items-center">
          <h2 className="text-[3rem] lg:text-[5rem] md:text-[5rem] font-extrabold">
            Create <span className="text-purple-300">T3</span> App
          </h2>

          <div className="border rounded p-10  m-3 bg-gray-700">
            <h1 className="pt-6 text-3xl text-blue-300 flex justify-center items-center">
              Examples:
            </h1>
            <div className="pt-6 text-2xl text-blue-500 flex flex-wrap justify-center items-center w-full">
              {data?.map((ex) => {
                return (
                  <div key={ex.id} className="m-2">
                    <div>{ex.id}</div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
