import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { getAuthSession } from "../server/common/get-server-session";
import { useSession } from "next-auth/react";

import LoggedOut from "../components/LoggedOut";

const Home: NextPage = () => {
  const { data: currentSession } = useSession();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center">
        {currentSession ? (
          <Link href={"/examples"}>
            <a>Examples</a>
          </Link>
        ) : (
          <LoggedOut />
        )}
      </div>
    </>
  );
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  return {
    props: {
      session: await getAuthSession(ctx),
    },
  };
};
export default Home;
